### ISSUE TITLE
Seg violation

### ISSUE THREAD

**Issue by cameronelliott** [lukechampine/noescape#2]
Thanks for writing this program, it's great!

When running 'testing' ReadTest(...), I got this seg violation, not sure of the root cause, didn't investigate deeply.

This occurred on a AMD64 (intel cpu) Mac Mini.

```
c@macmini ~/D/noescape (master) [1]> go test .
--- FAIL: TestRead (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd pc=0x10efd7e]

goroutine 6 [running]:
testing.tRunner.func1.2({0x11036e0, 0x11f3b20})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x11036e0, 0x11f3b20})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/lukechampine/noescape.TestRead(0xc0001004e0)
	/Users/c/Documents/noescape/noescape_test.go:21 +0x15e
testing.tRunner(0xc0001004e0, 0x1128d00)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
FAIL	github.com/lukechampine/noescape	0.089s
FAIL
c@macmini ~/D/noescape (master) [1]>
```

**Comment by magical** [comment]
I think the root cause is that Go 1.18 switched to a [register-based calling convertion](https://github.com/golang/go/issues/40724), so the assembly code in this package is no longer calling the function correctly. Supposedly the linker emits wrappers for some (all?) functions which adapt the old ABI to the new one, but i don't know if there's a way to access those from an itable.

Fortunately there's a much simpler method.

First, implement this utility function in assembly.
```go
// unsafeNoEscape returns its argument. Since it is marked as noescape, the compiler
// assumes that its argument doesn't escape, and since it is implemented in assembly
// the compiler can't look inside it to discover that we're lying. This has the effect of 
// hiding anything that happens to the returned value from the escape analyzer.
//go:noescape
func unsafeNoEscape(b []byte) []byte
```

(Here's an implementation for amd64:
```
// func unsafeNoEscape(b []byte) []byte
TEXT ·unsafeNoEscape(SB), NOSPLIT, $0-64
        MOVQ b_base+0(FP), AX
        MOVQ b_base+8(FP), BX
        MOVQ b_base+16(FP), CX
        MOVQ AX, ret_base+24(FP)
        MOVQ BX, ret_len+32(FP)
        MOVQ CX, ret_cap+40(FP)
        RET
```
)

Then Read and Write can be implemented like so:

```go
func Read(r io.Reader, b []byte) (int, error) { return r.Read(unsafeNoEscape(b)) }
func Write(w io.Writer, b []byte) (int, error) { return w.Write(unsafeNoEscape(b)) }
```

The method calls now happen in normal Go code, so they should always work even if the calling convention changes in the future. The assembly code should also be pretty stable; it is literally almost the simplest possible function (the only thing simpler would be a function which takes no args and returns nothing), so it seems like it should keep working as long as the compiler supports writing ABI0 functions in assembly — and keeping assembly working was one of the main reasons they kept ABI0 around. Or to put it another way, as long as all the crypto assembly in the standard library works without changes, this should too.

**Comment by magical** [comment]
An afterthought: probably need a `runtime.KeepAlive(b)` after the method call as otherwise the compiler might assume that `b` isn't needed during the call and optimize it away.

So Read would be, for example:
```go
func Read(r io.Reader, b []byte) (int, error) {
	n, err := r.Read(unsafeNoEscape(b))
	runtime.KeepAlive(b)
	return n, err
}
```

**Comment by lukechampine** [comment]
Clever! I'll happily merge if you submit a PR :)
